name: PlatformIO Checks

on: [push]

jobs:
  platfomio-validations:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python
      uses: actions/setup-python@v1
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install platformio
    - name: Compile Projects
      run: |
        FAIL=0
        cp config/MyPrivateConfig.sample.h config/MyPrivateConfig.h
        while read -r x; do
          proj=$(dirname "$x")
          if ! platformio run -d "$proj"
          then
            FAIL=1
          fi
        done <<< "$(find . -name platformio.ini )"
        rm config/MyPrivateConfig.h
        exit $FAIL
    - name: Run Static Checks
      run: |
        FAIL=0
        cp config/MyPrivateConfig.sample.h config/MyPrivateConfig.h
        while read -r x; do
          proj=$(dirname "$x")
          if ! platformio check -d "$proj" --fail-on-defect high --skip-packages
          then
            FAIL=1
          fi
        done <<< "$(find . -name platformio.ini )"
        exit $FAIL
